apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins-demo
  annotations:
    jenkins.io/job-full-name: "example-job"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: dev-team

